services:
  frontend:
    build:
      context: .
    environment:
      - NEXT_PUBLIC_NETWORK_TYPE=TESTNET
      - NEXT_PUBLIC_CHAIN_ID=AELF
      - NEXT_PUBLIC_SYMBOL=ELF
      - NEXT_PUBLIC_API_URL=http://localhost:4000
      - NEXT_PUBLIC_REMOTE_URL=http://localhost:3001
      - NEXT_PUBLIC_CMS_URL=http://192.168.66.62:3200
    ports:
      - 3000:3000