/*
 * @Author: aelf-lxy
 * @Date: 2023-07-31 14:37:10
 * @LastEditors: aelf-lxy
 * @LastEditTime: 2023-08-01 20:28:20
 * @Description: root layout
 */
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import RootProvider from './pageProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>heaer</div>
        <RootProvider>{children}</RootProvider>
        <footer className="text-3xl font-bold underline">2222</footer>
      </body>
    </html>
  );
}
