/*
 * @Author: aelf-lxy
 * @Date: 2023-07-31 14:37:10
 * @LastEditors: aelf-lxy
 * @LastEditTime: 2023-08-02 15:13:46
 * @Description: root layout
 */
import '@_style/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import RootProvider from './pageProvider';
import Header from '@_components/Header';
import Footer from '@_components/Footer';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <RootProvider>{children}</RootProvider>
        <Footer />
      </body>
      <Script
        src="https://lf1-cdn-tos.bytegoofy.com/obj/iconpark/icons_27664_13.df1dc658833885e2b6c5f25257eacd8b.js"
        strategy="afterInteractive"
      />
    </html>
  );
}
