name: Build and Deploy feature

on:
  push:
    branches: ['refactor/nextjs-13-develop']
env:
  DOTNET_INSTALL_DIR: "./.dotnet"

jobs:
  build-and-push-image:
    runs-on: block-explorer-runner
    permissions:
      contents: read
    outputs:
      short_sha: ${{ steps.vars.outputs.short_sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "short_sha=$calculatedSha" >> "$GITHUB_OUTPUT"

      - name: Create image tag
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.REPOSITORY_REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPOSITORY }}/aelf-block-explorer
          tags: |
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  dispatch:
    runs-on: block-explorer-runner
    needs: build-and-push-image
    steps:
      - name: Deploy
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TOK }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'AelfScanProject',
              repo: 'devops',
              workflow_id: 'aelf-explorer-server-deploy.yaml',
              ref: 'main',
              inputs: {
                env: 'production',
                appName: 'aelf-explorer-web',
                commit_sha: 'sha-${{ needs.build-and-push-image.outputs.short_sha }}',
              }
            })
